#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

void * fibonacci(void *);

// The main function takes a number of how many Fibonacci numbers to generate as a command line argument, creates a
// child thread to generate the Fibonacci sequence, and waits for the thread to complete before printing the sequence.
int main(int argc, char * argv[])
{
	// Check that the program was invoked with exactly one argument
	if (argc != 2)
	{
		printf("Usage: %s <number of the Fibonacci numbers>\n", argv[0]);
		return 1;
	}

	// Convert the stating number from a string to an integer
	int n = atoi(argv[1]);

	// Validate that the starting number is positive
	if (n <= 0)
	{
		printf("Number of Fibonacci numbers must be a positive integer.\n");
		return 1;
	}

	// Create a thread to generate the Fibonacci sequence
	pthread_t tid;
	pthread_attr_t attr;
	pthread_attr_init(&attr);
	pthread_create(&tid, &attr, fibonacci, &n);

	// Wait for the thread to complete
	void * fib_seq;
	pthread_join(tid, &fib_seq);

	// Print out the Fibonacci sequence generated by the child thread
	int *fib_ptr = (int *) fib_seq;
	for (int i = 0; i < n; i++)
		printf("%d ", fib_ptr[i]);
	printf("\n");

	// Free mempry used by the Fibonacci sequence array
	free(fib_seq);

	return 0;
}

// This function generates the Fibonacci sequence up to n and stores it in the array fib_seq
void * fibonacci(void *arg)
{
	// Convert the argument from a void pointer to an integer
	int n = *((int *) arg);

	// Allocate an array to hold the Fibonacci sequence
	int *fib_seq = (int *)malloc(n * sizeof(int));

	// Generate the Fibonacci Sequence
	fib_seq[0] = 0;
	fib_seq[1] = 1;
	for(int i = 2; i < n; i++)
		fib_seq[i] = fib_seq[i-1] + fib_seq[i-2];

	// Return a pointer to the Fibonacci sequence
	return (void *) fib_seq;
}
